CREATE DATABASE QLHT
CREATE TABLE THANHVIEN
(
	MSSV CHAR(10),
	HOTEN NVARCHAR(35),
	NGAYSINH DATETIME,
	VITRI NVARCHAR(55),
	EMAIL VARCHAR(100),
	PASS  VARCHAR(15),
	LASTMODIFIEDDATE DATETIME,
	LASTMODIFIEDUSER VARCHAR(100)
	PRIMARY KEY (MSSV)
)
GO
CREATE TRIGGER AUTOLOGGER ON THANHVIEN
AFTER INSERT, UPDATE
AS
BEGIN SET NOCOUNT ON
DECLARE 
@CURRENTDATETIME DATETIME = SYSUTCDATETIME(),
@CURRENTUSER VARCHAR(100) = SYSTEM_USER

UPDATE T
SET 
	LASTMODIFIEDDATE = @CURRENTDATETIME,
	LASTMODIFIEDUSER = @CURRENTUSER
FROM 
	THANHVIEN T
	inner join inserted i
	on t.MSSV=i.MSSV;
END
CREATE TABLE CONGVIEC
(
	MACV CHAR(10),
	TENCV NVARCHAR(25),
	TGBD  DATETIME,
	TGKT  DATETIME,
	TGTH  NVARCHAR(15),
	MADA  CHAR(10),
	STAWORK BIT, 
	PRIMARY KEY (MACV),
)
CREATE TABLE PHANCONG
(
	IDSTEAM CHAR(10),
	MSSV CHAR(10),
	MACV CHAR(10),
	PRIMARY KEY (IDSTEAM,MSSV,MACV)
)
CREATE TABLE DOAN
(
	MADA CHAR(10),
	TENDA NVARCHAR(55),
	NGAYNHAN DATETIME, 
	NGAYNOP  DATETIME,
	TGTH NVARCHAR(15),
	MAMH CHAR(10),
	TIENDO INT,
	PRIMARY KEY (MADA)
)
CREATE TABLE MONHOC
(
	MAMH CHAR(10),
	TENMH NVARCHAR(55),
	STC		INT,	
	TIENDO  INT,
	PRIMARY KEY (MAMH)
)
CREATE TABLE CTMH
(
	MSSV CHAR(10),
	MAMH CHAR(10),
	PRIMARY KEY (MSSV, MAMH),
)
CREATE TABLE SUBTEAM
(
	IDSTEAM CHAR(10),
	TENSTEAM NVARCHAR(55),
	SOLUONG INT,
	PRIMARY KEY (IDSTEAM)
)

ALTER TABLE PHANCONG
ADD CONSTRAINT L1
FOREIGN KEY (MSSV)
REFERENCES THANHVIEN(MSSV)

ALTER TABLE PHANCONG
ADD CONSTRAINT L2
FOREIGN KEY (MACV)
REFERENCES CONGVIEC(MACV)

ALTER TABLE CONGVIEC
ADD CONSTRAINT L3
FOREIGN KEY (MADA)
REFERENCES DOAN(MADA)

ALTER TABLE DOAN
ADD CONSTRAINT L4
FOREIGN KEY (MAMH)
REFERENCES MONHOC(MAMH)

ALTER TABLE CTMH
ADD CONSTRAINT L5
FOREIGN KEY (MAMH)
REFERENCES MONHOC(MAMH)

ALTER TABLE CTMH
ADD CONSTRAINT L6
FOREIGN KEY (MSSV)
REFERENCES THANHVIEN(MSSV)

ALTER TABLE PHANCONG
ADD CONSTRAINT L7
FOREIGN KEY (IDSTEAM)
REFERENCES SUBTEAM(IDSTEAM)

select *  from DOAN, CongViec, MonHoc where DOAN.MAMH=MONHOC.MAMH and CONGVIEC.MADA=DOAN.MADA and MONHOC.MAMH = 841048 
select * from CONGVIEC
select * from Congviec, MonHoc  
select count(MACV) from Congviec, MonHoc, DoAn where Stawork=1 and MonHoc.MAMH = 841048 and DOAN.MAMH=MONHOC.MAMH and CONGVIEC.MADA=DOAN.MADA
select count(MACV) from Congviec, MonHoc, DoAn where MonHoc.MAMH = 841048 and DOAN.MAMH=MONHOC.MAMH and CONGVIEC.MADA=DOAN.MADA
select * from Congviec, MonHoc, DoAn where MonHoc.MAMH = '841047' and DOAN.MAMH=MONHOC.MAMH and CONGVIEC.MADA=DOAN.MADA